name = "cf-ai-arqam-chat"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_SESSIONS"
class_name = "ChatSession"

[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]
